### ISSUE TITLE
Wine articles

### ISSUE THREAD

**Issue by mxdvl** [guardian/dotcom-rendering#5523]
Support horizontal rules better on these articles.

https://www.theguardian.com/food/2022/jul/22/crisp-white-wines-to-whet-the-appetite-aperitif-fiona-beckett

```css
hr {
  clear: left; /* required for floating images */
  border: none;
  height: 1px;
  background: #DCDCDC;
}
```
