### ISSUE TITLE
Labs AUS Container being rebuilt by CP

### ISSUE THREAD

**Issue by VDuczekW** [guardian/dotcom-rendering#7922]

**Comment by rhiannareechaye** [comment]
![Image](https://github.com/guardian/dotcom-rendering/assets/93542262/0bc94af1-0157-40f7-9f8d-75a1f0b62429)

**Comment by arelra** [comment]
> Padding is off when labs container has only 3 cards

This container is actually a thrasher.

Frontend applies extra styling from [_labs.scss](https://github.com/guardian/frontend/blob/main/static/src/stylesheets/module/commercial/_labs.scss#L31-L39) to reduce the side margins if the page does _not_ have a page skin:

```css
@media (min-width: 71.25em)
body:not(.has-page-skin) .dumathoin {
    margin: 0 calc(50% - 35.625rem);
}
```

Even with this extra styling the left col does not align perfectly on Frontend either
